# Generated by Django 6.0.3 on 2026-03-20 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Title')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('description', models.TextField(max_length=500, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('img', models.ImageField(blank=True, null=True, upload_to='products/images/%Y-%m-%d', verbose_name='Image')),
                ('category', models.CharField(choices=[('MOB', 'Mobiles'), ('LAP', 'Laptops'), ('TAB', 'Tablets'), ('MEN', 'Men Fashion'), ('WMN', 'Women Fashion'), ('TOY', 'Toyes'), ('LIT', 'Lighting')], max_length=6, verbose_name='Category')),
                ('available', models.BooleanField(default=True, verbose_name='Available')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'db_table': 'product',
                'ordering': ('-created_at',),
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__lte', 10000), ('quantity__gte', 0)), name='chk_product_quantity'), models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='chk_product_price')],
            },
        ),
    ]
