# Generated by Django 6.0.3 on 2026-03-20 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='img',
        ),
    ]
