# Generated by Django 6.0.3 on 2026-03-23 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_product_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='products/%Y-%m-%d', verbose_name='Image'),
        ),
    ]
