# Generated by Django 6.0.3 on 2026-03-17 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_authuser_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authuser',
            options={'ordering': ['-date_joined'], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterField(
            model_name='authuser',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='users/images/%Y-%m-%d', verbose_name='Image'),
        ),
    ]
