# Generated by Django 6.0.3 on 2026-04-06 15:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('vulner_type', models.CharField(choices=[('XSS', 'XSS'), ('SQLI', 'SQLI'), ('RCE', 'RCE'), ('IDOR', 'IDOR'), ('CSRF', 'CSRF'), ('PRIVILEGE_ESCALATION', 'Privilege Escalation'), ('BUSINESS_LOGIC', 'Business Logic'), ('SUBDOMAIN_TAKES_OVER', 'Subdomain Takes Over'), ('HOST_HEADER_INJECTION', 'Host Header Injection')], db_index=True, max_length=100, verbose_name='Type')),
                ('severity', models.SmallIntegerField(choices=[(0, 'Low'), (1, 'Medium'), (2, 'High'), (3, 'Critical')], db_index=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Serverity')),
                ('url', models.URLField(verbose_name='Url')),
                ('description', models.TextField(verbose_name='Description')),
                ('steps_to_reproduce', models.TextField(verbose_name='Steps To Reproduce')),
                ('poc', models.FileField(upload_to='vdp/%Y-%m-%d', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'png', 'jpg', 'jpeg', 'mov'])], verbose_name='Proof Of Concept')),
                ('impact', models.TextField(verbose_name='Impact')),
                ('recommended_fix', models.TextField(blank=True, null=True, verbose_name='Recommended Fix')),
                ('status', models.CharField(choices=[('NEW', 'New'), ('UNDER_REVIEW', 'Under Review'), ('RESOLVED', 'Resolved'), ('DUPLICATED', 'Duplicated'), ('INFORMATIVE', 'Informative'), ('OUT_OF_SCOPE', 'Out Of Scope')], db_index=True, default='NEW', max_length=30, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
