# Generated by Django 6.0.3 on 2026-03-27 14:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='wallet_number',
            field=models.CharField(default='000000000000', editable=False, max_length=12, unique=True, verbose_name='Wallet Number'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.CheckConstraint(condition=models.Q(('wallet_number__length', 12)), name='chk_wallet_wallet_number'),
        ),
    ]
