# Generated by Django 6.0.3 on 2026-04-04 18:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='wallet',
            name='chk_wallet_wallet_number',
        ),
        migrations.AlterField(
            model_name='wallet',
            name='wallet_number',
            field=models.CharField(editable=False, max_length=12, unique=True, validators=[django.core.validators.MinLengthValidator(12), django.core.validators.MaxLengthValidator(12)], verbose_name='Wallet Number'),
        ),
    ]
