# Generated by Django 6.0.3 on 2026-04-05 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_remove_wallet_chk_wallet_wallet_number_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='transaction',
            name='chk_transaction_amount',
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0.0)), name='chk_transaction_amount'),
        ),
    ]
